### ISSUE TITLE
simpleScale.letterBox doesn't draw properly

### ISSUE THREAD

**Issue by ImTiredRat** [tomlum/simpleScale#1]
`if gAspectRatio > sAspectRatio then --Screen aspect ratio is TALLER than game
		love.graphics.rectangle("fill", 0, 0, screenW/scale, -(yt/scale)-1)
		love.graphics.rectangle("fill", gameW, 0, screenW/scale, (yt/scale)+1)
	elseif gAspectRatio < sAspectRatio then --Screen aspect ratio is WIDER than game
		love.graphics.rectangle("fill", 0, 0, -(xt/scale)-1, screenH)
		love.graphics.rectangle("fill", gameW, 0, (xt/scale)+1, screenH)
  end`
here specifically doesn't work, I found that if the aspect ration is taller then game the width of the rectangles should be `gameW` instead of `screenW/scale` and if the aspect ration is wider then the game the height of the rectangles should be `gameH` instead of `screenH`

**Comment by tomlum** [comment]
Hey @Schwender-exe !  Thanks for pointing this out.  I have updated simpleScale in my personal usage of it, but haven't pushed anything in a while, because I didn't know anyone still used it!

I made a push that should fix this issue, and it slightly changes the api.  Let me know if anything is still not working.

Thanks for checking this out, and keeping me honest about updating my libraries haha.
